export enum FileExtensionEnum {
  JSON = 'json',
  XML = 'xml',
  CSV = 'csv',
  XLSX = 'xlsx',
  XLS = 'xls',
  DOCX = 'docx',
  DOC = 'doc',
  PDF = 'pdf',
  TXT = 'txt',
  HTML = 'html',
  PNG = 'png',
  JPG = 'jpg',
  JPEG = 'jpeg',
  GIF = 'gif',
  SVG = 'svg',
  MP4 = 'mp4',
  MOV = 'mov',
  AVI = 'avi',
  WMV = 'wmv',
  FLV = 'flv',
  MKV = 'mkv',
  MP3 = 'mp3',
  WAV = 'wav',
  WMA = 'wma',
  FLAC = 'flac',
  OGG = 'ogg',
  ZIP = 'zip',
  RAR = 'rar',
  TAR = 'tar',
  GZ = 'gz',
  BZ2 = 'bz2',
  ISO = 'iso',
  APK = 'apk',
  EXE = 'exe',
  DMG = 'dmg',
  DEB = 'deb',
  RPM = 'rpm',
  BIN = 'bin',
  SH = 'sh',
  BAT = 'bat',
  PS1 = 'ps1',
  PYTHON = 'py',
  JAVA = 'java',
  TYPESCRIPT = 'ts',
  JAVASCRIPT = 'js',
  C = 'c',
  CPP = 'cpp',
  CSHARP = 'cs',
  GO = 'go',
  RUBY = 'rb',
  PHP = 'php',
  SWIFT = 'swift',
  KOTLIN = 'kt',
  SCALA = 'scala',
  RUST = 'rs',
  PERL = 'pl',
  LUA = 'lua',
  SQL = 'sql',
  CSS = 'css',
  SASS = 'sass',
  SCSS = 'scss',
  LESS = 'less',
  STYLUS = 'styl',
  YAML = 'yaml',
  TOML = 'toml',
  INI = 'ini',
  CFG = 'cfg',
  CONF = 'conf',
  WEBP = 'webp',
  PROPERTIES = 'properties',
}

export const IMAGE_FILE_TYPES = [
  FileExtensionEnum.PNG,
  FileExtensionEnum.JPG,
  FileExtensionEnum.JPEG,
  FileExtensionEnum.GIF,
  FileExtensionEnum.SVG,
  FileExtensionEnum.WEBP,
];



